# Units file

# Envs
conda_envs: 
  qc: "workflow/envs/qc.yaml"
  umi_tools: "workflow/envs/umi_tools.yaml"
  preprocessing: "workflow/envs/preprocessing.yaml"
  fastq_screen: "workflow/envs/fastq_screen.yaml"
  aligners: "workflow/envs/aligners.yaml"
  qualimap: "workflow/envs/qualimap.yaml"
  rseqc: "workflow/envs/rseqc.yaml"
  quantification: "workflow/envs/quantification.yaml"

# Enable processes
umi_processing: 
  enabled: True

# Genome information
genome:
  name: hg38
  index: resources/genome/hg38_genome_index
  annotation_gtf: resources/annotations/hg38/Homo_sapiens.GRCh38.111.gtf
  annotation_bed: resources/annotations/hg38/Homo_sapiens.GRCh38.111.bed

# Parameters
parameters:

  fastqc: 
    extra: ""

  bbudk:
    adapters: "resources/trim_files/adapters.fa.gz"
    polyA: "resources/trim_files/polyA.fa.gz"
    extra: "k=13 ktrim=r mink=5 qtrim=r trimq=20 useshortkmers=t minlength=20"
  
  fastq_screen:
    config: "resources/fastq_screen_files/FastQ_Screen_Genomes/fastq_screen.conf",
    aligner: bowtie2
    extra: ""

  multiqc:
    extra: "--verbose"

  alignment: 
    extra: | # Chequear cuales son default y borrarlos
      --genomeLoad LoadAndKeep
      --outFilterType BySJout 
      --outFilterMultimapNmax 25
      --alignSJoverhangMin 8
      --alignSJDBoverhangMin 1
      --outFilterMismatchNmax 999
      --outFilterMismatchNoverLmax 0.3
      --alignIntronMin 20
      --alignIntronMax 1000000
      --alignMatesGapMax 1000000
      --limitBAMsortRAM 64000000000
      --outSAMattributes NH HI AS NM MD

  bam_indexing: 
    extra: ""

  qualimap:
    genome: HUMAN
    extra_single: "-hm 3 -nr 1000 -p strand-specific-forward"
    extra_multi: ""
    extra_rnaseq: "-p strand-specific-forward"

  rseqc_strand:
    extra: ""

  samtools_qc:
    extra: ""

  feature_counts:
    extra: "-O -F GTF -t gene -g gene_id --extraAttributes gene_name,transcript_name -s 1"

  umi_extract:
    extract_method: "regex"
    extra: "--bc-pattern='^(?P<umi_1>.{6})(?P<discard_1>.{4}).*'" 
  
  umi_dedup:
    method: "unique"
    extra:  "--multimapping-detection-method=NH"


# Resources
resources:
  default:
    threads: 1
    mem_mb: 4096
    runtime: 10

  fastqc:
    threads: 2
    mem_mb: 4096
    runtime: 10

  bbduk:
    threads: 8
    mem_mb: 8192
    runtime: 60
  
  fastq_screen:
    threads: 8
    mem_mb: 10240
    runtime: 10
  
  alignment:
    threads: 1
    mem_mb: 64000
    runtime: 60
  
  bam_indexing:
    threads: 8
    mem_mb:  4096
    runtime: 10
  
  qualimap:
    threads: 8
    mem_mb:  16384
    runtime: 10
  
  rseqc_strand:
    threads: 4
    mem_mb:  8192
    runtime: 10
  
  feature_counts:
    threads: 8
    mem_mb:  64000
    runtime: 120
  
  umi_extract:
    threads: 8
    mem_mb: 8192
    walltime: 60

  umi_dedup:
    threads: 8
    mem_mb:  32000
    runtime: 120
