conda_envs: 
  qc: "envs/qc.yml"
  rna_seq_3: "envs/rna_seq_3.yml"
  rna_seq_3_v2 : "envs/rna_seq_3_v2.yml"

sample:
  - MEC1-MYC-OE-S1
  - MEC1-MYC-OE-S2
  - MEC1-MYC-OE-S3
  - MEC1-MYC-WT-S1
  - MEC1-MYC-WT-S2
  - MEC1-MYC-WT-S3
  - PGA-MYC-OE-COMBO
  - PGA-MYC-OE-S1
  - PGA-MYC-OE-S2
  - PGA-MYC-OE-S3
  - PGA-MYC-WT-S1
  - PGA-MYC-WT-S2
  - PGA-MYC-WT-S3

umi_processing: 
  enabled: True
  pattern: '^(?P<umi_1>.{6})(?P<discard_1>.{4}).*' 

seq_lane:
  - L008

fastq_screen:
  aligner: bowtie2

genome_index: resources/genome/hg38_genome_index
annotation: resources/annotations/hg38/Homo_sapiens.GRCh38.111.gtf
reference_bed: resources/annotations/hg38/Homo_sapiens.GRCh38.111.bed
fastq_screen_conf: resources/fastq_screen_files/FastQ_Screen_Genomes/fastq_screen.conf
fastq_screen_aling: bowtie2

qualimap:
  genome: HUMAN
  mem: 18G